@{
    RootModule        = 'setup.psm1'
    ModuleVersion     = '0.1.0'
    FunctionsToExport = @(
        'Invoke-DocsLocal'
        'Invoke-DocsWorkflowLocal'
        'Write-Step'
        'Write-Success'
        'Write-WarningMessage'
        'Test-CommandAvailable'
        'Update-SessionPath'
        'Get-NpxCommand'
        'Assert-CommandAvailable'
        'Invoke-NativeCommand'
        'Test-McpServerRegistered'
        'Resolve-OrCreatePath'
        'New-ProjectStructure'
        'New-ProjectFile'
        'New-Gitignore'
        'New-EnvExample'
        'New-ReadmeFile'
        'New-ArchitectureFile'
        'New-AdtTemplate'
        'New-ClaudeInstructions'
        'New-AgentsInstructions'
        'Initialize-ProjectGit'
        'Invoke-LanguageStarter'
        'Test-ProjectBuildable'
        'Test-ProjectTestable'
        'New-ProjectInitialCommit'
        'Invoke-SetupDocs'
        'Invoke-SetupMacos'
        'Invoke-SetupProject'
        'Invoke-SetupUbuntu'
        'Invoke-SetupWindows'
        'Invoke-SetupWorkstation'
        'Invoke-Setup'
        'Invoke-SetupStarterNode'
        'Invoke-SetupStarterPython'
        'Invoke-InstallClaudeMem'
        'Invoke-InstallClaudeMemory'
        'Invoke-InstallDatabaseMcp'
        'Invoke-InstallFilesystemMcp'
        'Invoke-InstallGithubMcp'
        'Invoke-InstallGraphify'
        'Invoke-InstallPlaywrightMcp'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}